package com.shekharhandigol.aiarticlesummarizer.util


const val DATABASE_NAME = "ARTICLE_TABLE"

const val DATASTORE_FILE_NAME = "AI_ARTICLE_SUMMARISER_DATASTORE_FILE"
const val DATASTORE_DARK_MODE = "DARK_MODE_SETTINGS"
const val DATASTORE_PROMPT_SETTINGS = "GEMINI_PROMPT_SETTINGS"
const val DATASTORE_GEMINI_MODEL_NAME = "GEMINI_MODEL_NAME"
